### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by D3AdCa7** [litanlitudan/skyagi#45]
![20230425-020326](https://user-images.githubusercontent.com/5355885/234079277-d6124eed-7061-44d3-ad30-69edbb95cce9.jpeg)

**Comment by litanlitudan** [comment]
Thanks @D3AdCa7 for pointing it out. 
It's resolved in PR: https://github.com/litanlitudan/skyagi/pull/47
All feedbacks are appreciated!
