### ISSUE TITLE
Integrate with langchain-serve to expose `skyagi-as-a-service`?

### ISSUE THREAD

**Issue by deepankarm** [litanlitudan/skyagi#54]
Would you be open to integrating skyagi with [langchain-serve](https://github.com/jina-ai/langchain-serve)?

- You won't have to handle API routes yourself (we use FastAPI & Jina to handle/scale the routes).
- Can enable streaming using WebSocket & human-in-the-loop integration - this is a great addition for chat scenarios.
- Local to cloud-ready in just one command - lc-serve deploy local/jcloud <app>
- Serverless/autoscaling endpoints with automatic tls certs on Cloud.
- Already includes [babyagi-as-a-service](https://github.com/jina-ai/langchain-serve#-babyagi-as-a-service)!

Disclaimer: I'm the primary author of langchain-serve. Would be happy to collaborate on this!

**Comment by litanlitudan** [comment]
Sure, sounds like an amazing idea! Let's do it! @deepankarm

**Comment by qizheng7** [comment]
Hi @deepankarm , thanks for reaching out to us. I had a brief look at the langchain-serve. One question I failed finding the answer: how does it support other serving / deployment options other than JINA cloud?

we can have a quick chat if it helps answer the question.  Regards.

**Comment by deepankarm** [comment]
@qizheng7 Thanks for trying out langchain-serve. 

langchain-serve tightly integrates with FastAPI & Jina. Hence for Cloud deployment, we only support Jina Cloud right now. There are a few options if you cannot use Jina Cloud directly - We can provide an option to expose `docker-compose` or K8S yamls. With this, users need to take care of their deployments/infrastructure. 

Happy to have you on our slack for further discussion - https://jina.ai/slack/

**Comment by qizheng7** [comment]
thanks @deepankarm . We will look into the docker and K8s option of langchain-serve. And will reach you out if we have any additional question. thanks.

**Comment by qizheng7** [comment]
@deepankarm could you please point me to the codes where they sit? I can take a look at the codes first.

**Comment by litanlitudan** [comment]
@deepankarm Could you point us to how to set thing up on Jina cloud? We are trying to host an instance of SkyAGI as API so that people can easily tryout and feel the excitement of generative agent in the first hand. It would be great if we can leverage Jina Cloud‘s capability to bring this up in a timely manner 🙏🙏🙏

**Comment by deepankarm** [comment]
@litanlitudan The first step is to refactor the current code and add `@serving` decorator wherever the API is needed. To enable streaming and human-in-the-loop, your use case might need a WebSocket API. 

Here are a few open-source examples that might help you.

- [pdfGPT's `ask` REST API](https://github.com/bhaskatripathi/pdfGPT/blob/7d103c71a535f81de4f106d153f15804a5a18146/api.py#L156)
- [ChatGLM's `predict` REST API](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/blob/master/jina_serving.py#L238)
- [Megabot's `ask` REST API](https://github.com/deepankarm/megabots/blob/518c0d0784ae1042690b67e02f2fe57ef643aae2/megabots/api.py#L10)
- [Babyagi-as-a-service `baby_agi` Websocket API](https://github.com/jina-ai/langchain-serve/blob/09107b0ee98a194befe9fcb3c48ae884c34dea4d/lcserve/apps/babyagi/app.py#L11)
- [Human-in-the-loop `hitl` Websocket API](https://github.com/jina-ai/langchain-serve/blob/c0af0de263c4494ce457faa4c9b82cab61992c5a/examples/websockets/hitl/hitl.py#L12)

Once the API is ready, you can use **[lc-serve deploy](https://github.com/jina-ai/langchain-serve#-custom-apps-to-production-in-4-simple-steps)** commands for local & Jina AI Cloud deployments.  

@qizheng7 `langchain-serve` expands on [Jina](https://github.com/jina-ai/jina) and Jina has features to [export to docker-compose/kubernetes](https://docs.jina.ai/concepts/orchestration/flow/#export) YAMLs. If needed, we can opt to export via a new CLI options in langchain-serve.

**Comment by qizheng7** [comment]
The websocket APIs are built on top of langchain-serve already.

**Comment by j2l** [comment]
Excuse my interruption, I can't find how to get docker-compose for skyagi and only this issue speaks about it.
Would you please explain?

> The websocket APIs are built on top of langchain-serve already.
Skyagi API, or the others mentioned above?

**Comment by qizheng7** [comment]
@j2l 
- Skyagi CLI is a pure python based framework. You can find the instruction [here](https://github.com/litanlitudan/skyagi#quick-start).
- Skyagi Websocket API is running on JINA AI, and the instructions are [here](https://github.com/litanlitudan/skyagi/tree/main/skyagi-api).
