### ISSUE TITLE
LiveError: Only one live display may be active at once

### ISSUE THREAD

**Issue by cat-stack-boop** [litanlitudan/skyagi#56]
I get this error , rich.live.Live object.

**Comment by litanlitudan** [comment]
Hi @cat-stack-boop, yes, this is indeed an error. It's mainly because our code is not robust or async safe enough to handle the lousy connection to OpenAI api. I am working on this, thanks for the feedback! @cat-stack-boop

**Comment by cat-stack-boop** [comment]
Great thanks for the quick response.

**Comment by litanlitudan** [comment]
Just made a quick patch release https://github.com/litanlitudan/skyagi/pull/57 @cat-stack-boop 
Will file an appropriate fix during the weekend.

**Comment by qizheng7** [comment]
Hi @cat-stack-boop the proper fix is through this PR #64 .

**Comment by cat-stack-boop** [comment]
@qizheng7  Thanks!
