### ISSUE TITLE
How to debug the code locally?

### ISSUE THREAD

**Issue by sunlanchang** [litanlitudan/skyagi#66]
I am able to run skyagi locally by following the instruction from the readme, but I want to debug the code locally by using vscode or other debug tools, how should I do? Thanks!

**Comment by qizheng7** [comment]
Hi @sunlanchang , you can use [python debugger pdb](https://docs.python.org/3/library/pdb.html) to set breakpoint and debug. Hope this helps.

**Comment by litanlitudan** [comment]
Maybe it's beneficial to have some tutorial setting up VScode Debugger, even thought it not part of this project's scope. Will find some to do this, thanks for the feedback! @sunlanchang

**Comment by sunlanchang** [comment]
I only have a free OpenAI account, which limits me to 3 requests per minute. I'd like to modify the code to meet this requirement, such as adding sleep time to reduce the request rate. Is there a command to run the repo code locally without installing the library? For example, `python -m skyagi/src/cli.py` (which not works), or some other command like this. Thanks! 🫡
